branches:
  - name: "master"
    protection:
      enforce_admins: false
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 1
      required_status_checks:
        contexts:
          - "Code Coverage (7.4, locked)"
          - "Coding Standards (7.2, locked)"
          - "Dependency Analysis (7.4, locked)"
          - "Mutation Tests (7.4, locked)"
          - "Static Code Analysis (7.4, locked)"
          - "Tests (7.2, highest)"
          - "Tests (7.2, locked)"
          - "Tests (7.2, lowest)"
          - "Tests (7.3, highest)"
          - "Tests (7.3, locked)"
          - "Tests (7.3, lowest)"
          - "Tests (7.4, highest)"
          - "Tests (7.4, locked)"
          - "Tests (7.4, lowest)"
        strict: false
      restrictions:
        apps: []
        teams: []
        users:
          - "iterica-bot"

labels:
  - name: "bug"
    color: "ee0701"
    description: ""

  - name: "dependency"
    color: "0366d6"
    description: ""

  - name: "enhancement"
    color: "0e8a16"
    description: ""

  - name: "merge"
    color: "6f42c1"
    description: ""

  - name: "question"
    color: "cc317c"
    description: ""

  - name: "security"
    color: "ee0701"
    description: ""

  - name: "stale"
    color: "eeeeee"
    description: ""

repository:
  allow_merge_commit: true
  allow_rebase_merge: false
  allow_squash_merge: false
  archived: false
  default_branch: "master"
  delete_branch_on_merge: true
  description: "Navigation core library"
  has_downloads: true
  has_issues: true
  has_pages: false
  has_projects: false
  has_wiki: false
  name: "navigation-core"
  private: false
  topics: "php, navigation"
